language: ruby

sudo: false

env:
  - NODE_JS_VERSION='0.10'
  - NODE_JS_VERSION='0.11'

install:
  - nvm use $NODE_JS_VERSION

script:
  - true

rvm:
  - '2.1.4'
  - '1.9.3'

deploy:
  provider: s3
  access_key_id: "YOUR AWS ACCESS KEY"
  secret_access_key: "YOUR AWS SECRET KEY"
  bucket: "S3 Bucket"
  on:
    condition: $NODE_JS_VERSION = '0.10' && $TRAVIS_RUBY_VERSION = '2.1.4'
